Feature/bouncy pixels animation
sensorlab030/led-wall pull request #14
Opened 2018-05-08 09:12 UTC by jonasgrootkormelink

2018-05-15 14:09 UTC, wilcotomassen requested changes

2018-05-15 14:09 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/bouncypixels/BouncyPixelsAnimation.java
> +	BouncyPixelSystem  bouncypixelssytem;
Fix member visibility here

2018-05-15 14:09 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/bouncypixels/BouncyPixelSystem.java
> +	BouncyPixelsAnimation parent;
Fix member visibility here

2018-05-15 14:09 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/bouncypixels/BouncyPixel.java
> +	public void update() {
This method should also use delta time to decouple animation speed and frame rate

2018-05-15 14:09 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/bouncypixels/BouncyPixel.java
> +	BouncyPixelSystem parent;
Again: member visibility: parent has no visibility declared, do all other members need to be public?

2018-05-15 14:09 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/bouncypixels/BouncyPixel.java
> +	public float diameter;
If you work with radius here, it saves you a boatload of diameter / 2 in the update functions. Makes for better performance.

2018-05-15 14:09 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/bouncypixels/BouncyPixelSystem.java
> +		float diameter = 1; // <-- Because it are pixels we want this to be set to 1
If this is fixed (static) why isn't it a constant? Then it doesn't need to be in memory and not passed around in methods.

2018-05-15 14:09 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/bouncypixels/BouncyPixelsAnimation.java
> +public class BouncyPixelsAnimation extends BaseAnimation{
This class feels like it's just a wrapper around BouncyPixelSystem. I think you can merge the whole BouncyPixelSystem in this class without losing any clarity.

2018-05-15 14:09 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/bouncypixels/BouncyPixelsAnimation.java
> +			if(bouncypixelssytem.bouncypixels.size() > MAX_AMOUNT_BOUNCY_PIXELS) {
Wouldn't it make sense to give each BouncyPixel a lifetime, and then remove it once it dies?

2018-05-15 14:10 UTC, wilcotomassen requested changes
I think you can Merge BouncyPixelSystem into BouncyPixelAnimation and nest BouncyPixel in BouncyPixelAnimation to remove the need for a package

2018-06-04 07:28 UTC, jonasgrootkormelink commented
@wilcotomassen I think we can merged this branch into develop.

2018-06-04 11:45 UTC, wilcotomassen approved these changes

2018-06-04 12:12 UTC, merged