Feature/horizontal waves animation
sensorlab030/led-wall pull request #15
Opened 2018-05-08 13:16 UTC by jonasgrootkormelink

2018-05-15 13:58 UTC, wilcotomassen requested changes
First: fix the merge conflicts with develop (probably just the gitignore and animationManager

Then: Can you move HorizontalWave into HorizontalWavesAnimation and remove the horizontalwaves package? Makes it all a bit more compact

2018-05-15 13:58 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/horizontalwaves/HorizontalWave.java
> +		for(int x = 0; x <= parent.PIXEL_RESOLUTION_X; x++) {
Use a static accessor here: e.g. BaseAnimation.PIXEL_RESOLUTION_X

2018-05-15 13:58 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/horizontalwaves/HorizontalWave.java
> +			float y = parent.parent.map(perlinNoise, 0, 1, 0, parent.PIXEL_RESOLUTION_Y);
Use a static accessor here as well

2018-05-15 13:58 UTC, wilcotomassen commented on client/src/nl/sensorlab/videowall/animation/baseanimations/horizontalwaves/HorizontalWave.java
> +		offsetSpeed += offsetSpeedIncrements;
Use delta time here to decouple animation speed and framerate

2018-06-04 07:34 UTC, jonasgrootkormelink commented
@wilcotomassen I think we can merged this branch into develop. I've made the requested changes!

2018-06-04 11:45 UTC, wilcotomassen approved these changes

2018-06-04 11:46 UTC, merged